name: 💾 Cache and Install
on:
  workflow_call:

permissions:
  actions: write
  contents: read

jobs:
  cache-and-install:
    name: Cache and Install
    runs-on: ubuntu-latest
    outputs:
      node: ${{ steps.node.outputs.node }}
      pnpm: ${{ steps.pnpm.outputs.pnpm }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        id: pnpm-install
        with:
          version: 7.11.0
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Set node version
        id: node
        run: |
          echo "::set-output name=node::16"

      - name: Set pnpm version
        id: pnpm
        run: |
          echo "::set-output name=pnpm::7.11.0"
